* Introduction & Rules
Hello!

Sorry if you're getting this problem set for the second time. We're
still fine-tuning our process, and there are a few kinks to work out.

That being said: enclosed are the cryptography challenges you
requested.

To be clear, this is a subset comprising the first eight problems. You
can get the second set by solving these first. Feel free to send us
solutions in the language of your choice along with answers in
comments or the body of your email.

If you get stuck or need clarification on something, don't hesitate to
ask! We're happy to help.

THE RULES AND THEY ARE SOMEWHAT IMPORTANT:

- Please do not share this with anyone or post solutions online. If you
  have any friends who would like to participate, send them our way and
  we will set them up.

- When you mail your solutions, please CC responses@matasanocryptopals.com.

- Please prefix the subject of your mail with RESPONSE:.

* 1. Convert hex to base64 and back.

The string:

  49276d206b696c6c696e6720796f757220627261696e206c696b65206120706f69736f6e6f7573206d757368726f6f6d

should produce:

  SSdtIGtpbGxpbmcgeW91ciBicmFpbiBsaWtlIGEgcG9pc29ub3VzIG11c2hyb29t

Now use this code everywhere for the rest of the exercises. Here's a
simple rule of thumb:

  Always operate on raw bytes, never on encoded strings. Only use hex
  and base64 for pretty-printing.
** Solution
#+BEGIN_SRC emacs-lisp
  (defun hex (bytes)
    (loop for x across bytes
         concat (format "%02x" x)))
  
  (defun unhex (str)
    (apply 'string
           (loop for i below (length str) by 2
              collect (string-to-number (string (aref str i) (aref str (1+ i))) 16))))
#+END_SRC
* 2. Fixed XOR
  
Write a function that takes two equal-length buffers and produces
their XOR sum.

The string:

 1c0111001f010100061a024b53535009181c

... after hex decoding, when xor'd against:

 686974207468652062756c6c277320657965

... should produce:

 746865206b696420646f6e277420706c6179

** Solution
#+BEGIN_SRC emacs-lisp
  (defun fixed-xor (str1 str2)
    (apply 'string
           (loop for a across str1
                 for b across str2
                 collect (logxor a b))))
  
  ;; (hex (fixed-xor (unhex "1c0111001f010100061a024b53535009181c")
  ;;                 (unhex "686974207468652062756c6c277320657965")))
#+END_SRC
* 3. Single-character XOR Cipher

The hex encoded string:

      1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736

... has been XOR'd against a single character. Find the key, decrypt
the message.

Write code to do this for you. How? Devise some method for "scoring" a
piece of English plaintext. (Character frequency is a good metric.)
Evaluate each output and choose the one with the best score.

Tune your algorithm until this works.
** Solution
We assume the text contains only letters numbers and punctuation. As far as letter frequency is concerned, we use information from Wikipedia and assume that the decoded text has the following letters in decreasing frequency: eaiou and maybe jxqz being very very odd.

http://en.wikipedia.org/wiki/Letter_frequency#Relative_frequencies_of_letters_in_the_English_language
#+BEGIN_SRC emacs-lisp
  (defun fruit-loop (txt)
    (loop with T = (unhex txt)
         for O = (setq O (cons l (fixed-xor T (make-string (length T) l)))) then (setq O (cons l (fixed-xor T (make-string (length T) l))))
         for l from ?A to ?Z
         when (string-match-p "[A-Za-z0-9 \.!'\"!?-]" (cdr O))
          collect O
         ))
  
  (fruit-loop "1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736")
  
  ; so the letter is X, but now use some function to rate the output
  
#+END_SRC
* 4. Detect single-character XOR

One of the 60-character strings at:

  https://gist.github.com/3132713

has been encrypted by single-character XOR. Find it. (Your code from
#3 should help.)

// ------------------------------------------------------------

* 5. Repeating-key XOR Cipher

Write the code to encrypt the string:

  Burning 'em, if you ain't quick and nimble
  I go crazy when I hear a cymbal

Under the key "ICE", using repeating-key XOR. It should come out to:

  0b3637272a2b2e63622c2e69692a23693a2a3c6324202d623d63343c2a26226324272765272a282b2f20430a652e2c652a3124333a653e2b2027630c692b20283165286326302e27282f

Encrypt a bunch of stuff using your repeating-key XOR function. Get a
feel for it.

// ------------------------------------------------------------
** Solution
#+BEGIN_SRC emacs-lisp
  (defun fixed-xor (str1 key)
    (apply 'string
           (loop with l = (length key)
                 for a across str1
                 for i = 0 then (mod (1+ i) l)
                 collect (logxor a (aref key i)))))
  
  ; (hex (fixed-xor "Burning 'em, if you ain't quick and nimble\nI go crazy when I hear a cymbal" "ICE"))
#+END_SRC
* 6. Break repeating-key XOR

The buffer at the following location:

 https://gist.github.com/3132752

is base64-encoded repeating-key XOR. Break it.

Here's how:

a. Let KEYSIZE be the guessed length of the key; try values from 2 to
(say) 40.

b. Write a function to compute the edit distance/Hamming distance
between two strings. The Hamming distance is just the number of
differing bits. The distance between:

  this is a test

and:

  wokka wokka!!!

is 37.
#+BEGIN_SRC emacs-lisp
(defun hammond (clarkson may)
  (loop with laps = 0
        for a across clarkson
        for b across may
        do (loop repeat 8
              for rox = (logxor a b) then (lsh rox -1)
                do (when (= (logand rox 1) 1)
                     (incf laps)))
       finally return laps))

; (hammond "this is a test" "wokka wokka!!!")

#+END_SRC
c. For each KEYSIZE, take the FIRST KEYSIZE worth of bytes, and the
SECOND KEYSIZE worth of bytes, and find the edit distance between
them. Normalize this result by dividing by KEYSIZE.

d. The KEYSIZE with the smallest normalized edit distance is probably
the key. You could proceed perhaps with the smallest 2-3 KEYSIZE
values. Or take 4 KEYSIZE blocks instead of 2 and average the
distances.

e. Now that you probably know the KEYSIZE: break the ciphertext into
blocks of KEYSIZE length.

f. Now transpose the blocks: make a block that is the first byte of
every block, and a block that is the second byte of every block, and
so on.

g. Solve each block as if it was single-character XOR. You already
have code to do this.

e. For each block, the single-byte XOR key that produces the best
looking histogram is the repeating-key XOR key byte for that
block. Put them together and you have the key.

* 7. AES in ECB Mode

The Base64-encoded content at the following location:

    http://cryptopals.com/static/challenge-data/7.txt

Has been encrypted via AES-128 in ECB mode under the key

    "YELLOW SUBMARINE".

(I like "YELLOW SUBMARINE" because it's exactly 16 bytes long).

Decrypt it.

Easiest way:

Use OpenSSL::Cipher and give it AES-128-ECB as the cipher.

// ------------------------------------------------------------

* 8. Detecting ECB

At the following URL are a bunch of hex-encoded ciphertexts:

   https://gist.github.com/3132928

One of them is ECB encrypted. Detect it.

Remember that the problem with ECB is that it is stateless and
deterministic; the same 16 byte plaintext block will always produce
the same 16 byte ciphertext.

// ------------------------------------------------------------
